# Generated by Django 5.0.7 on 2024-07-15 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='titel',
            new_name='title',
        ),
    ]
